# Generated by Django 3.2 on 2021-04-25 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pr_num', models.IntegerField(verbose_name='pull request')),
                ('additions', models.IntegerField()),
                ('deletions', models.IntegerField()),
                ('sha', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('constitutional', models.BooleanField(default=False, help_text='This is true only for amendments to the constitution')),
                ('prop_date', models.DateTimeField(auto_now_add=True, verbose_name='date proposed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('no_votes', models.ManyToManyField(blank=True, related_name='no_votes', to=settings.AUTH_USER_MODEL)),
                ('yes_votes', models.ManyToManyField(blank=True, related_name='yes_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
