# Generated by Django 3.2 on 2021-04-25 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('elections', '0001_initial'), ('elections', '0002_auto_20210419_0523'), ('elections', '0003_auto_20210423_1737'), ('elections', '0004_auto_20210424_1741')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pr_num', models.IntegerField(verbose_name='pull request')),
                ('prop_date', models.DateTimeField(auto_now_add=True, verbose_name='date proposed')),
                ('constitutional', models.BooleanField(default=False, help_text='This is true only for amendments to the constitution')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('no_votes', models.ManyToManyField(blank=True, related_name='no_votes', to=settings.AUTH_USER_MODEL)),
                ('yes_votes', models.ManyToManyField(blank=True, related_name='yes_votes', to=settings.AUTH_USER_MODEL)),
                ('active', models.BooleanField(default=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('sha', models.CharField(default='08a268f4b55c8b798c94745592337e037b209fcb', max_length=40)),
            ],
        ),
    ]
